### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by gaurav-nelson** [stackrox/kube-linter-action#1]
Thanks @neilcar for creating the action. 

Would it be possible to do a proper tagging for this project please?

Maybe good starting point is here: https://github.com/actions/checkout
They are using versions like:
```
v2 -> v2.0.0
v1 -> v1.2.0
v1.1.0
v1.0.0
```
It would be really handy to use something like `v1` instead of specifying the exact version only `v0.0.2`:
```
    - uses: stackrox/kube-linter-action@v1
```
It will save folks from changing the "exact versions" when you release new version.

For example this project can be handy for automating the release process: https://github.com/haya14busa/action-update-semver

Thank you...

**Comment by neilcar** [comment]
Excellent idea.  I've implemented it.  There's now an @v1 and I configured the action you suggested to automate that.
