### ISSUE TITLE
Provide a way to specify which kube-linter version to use

### ISSUE THREAD

**Issue by bznein** [stackrox/kube-linter-action#8]
First of all, thank you for the GH action, it is extremely helpful!

however, we encountered an issue since 2 days ago, when kube-linter 0.2.4 was released (https://github.com/stackrox/kube-linter/releases/tag/0.2.4, introducing a new check: "non-isolated-pod".

Our yaml files currently violate this rule, making our test fails. 
While we can easily workaround this by excluding this particular check in our config file, I think it would be good to add a parameter to the action that can allow users to use a specific version rather than `latest` (which is [currently hardcoded](https://github.com/stackrox/kube-linter-action/blob/main/action.yml#L28)) This way we would be sure that new releases won't break our listing tests and we can update as needed

**Comment by viswajithiii** [comment]
Thanks for filing and sending the PR, @bznein. This is now fixed 🙂

**Comment by bznein** [comment]
Thank you for the quick turnaround and release for this!
